[dependencies]
apt = ["aaa", "bbb", "ccc"]
pip = ["aaa", "bbb"]

[large-dependencies]
apt = ["aaa"]
pip = ["ccc", "ddd"]

[target.aarch64-unknown-linux-gnu.dependencies]
apt = ["aarch64"]

[target.x86_64-unknown-linux-gnu.dependencies]
apt = ["x86_64"]
